// Code generated by "stringer -type=GatewayType"; DO NOT EDIT.

package surls

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Inmem-1]
}

const _GatewayType_name = "Inmem"

var _GatewayType_index = [...]uint8{0, 5}

func (i GatewayType) String() string {
	i -= 1
	if i < 0 || i >= GatewayType(len(_GatewayType_index)-1) {
		return "GatewayType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _GatewayType_name[_GatewayType_index[i]:_GatewayType_index[i+1]]
}
